2020-06-08 20:11:55,070 ERROR: Exception on /home [POST] [in c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\routes.py", line 20, in index
    body=r.fetch(page)
  File "C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\urlParse.py", line 83, in fetch
    urllib.request.urlretrieve(image_path, fullfilename+'.jpg')
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 509, in open
    req = Request(fullurl, data)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 328, in __init__
    self.full_url = url
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 354, in full_url
    self._parse()
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/image/dv_web_D180001002372539/139352/acer-aspire-3-ed009-156-baerbar-computer-sort.jpg?$prod_all4one$'
2020-06-08 20:12:26,340 INFO: Crates startup [in C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\__init__.py:30]
2020-06-08 20:19:11,718 INFO: Crates startup [in C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\__init__.py:30]
2020-06-08 20:20:21,353 INFO: Crates startup [in C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\__init__.py:30]
2020-06-08 20:20:22,338 ERROR: Exception on /home [POST] [in c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\augus\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\routes.py", line 20, in index
    body=r.fetch(page)
  File "C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\urlParse.py", line 138, in fetch
    price = price.text
AttributeError: 'NoneType' object has no attribute 'text'
2020-06-08 20:24:08,201 INFO: Crates startup [in C:\Users\augus\OneDrive\Skrivebord\CratesAppFeature\app\__init__.py:30]
